### ISSUE TITLE
Update database name configurations to use the name from the secret

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-configurations#98]
Database names have been moved into the secrets for the various databases.  However database name references are still being set discretely in some places.  The database configurations themselves were updated, but some client services (`api`, `msg-queue-worker`, and `agent`) were not.

Currently looks like this:
```
  - name: DATABASE_NAME
    value: ${DATABASE_NAME}
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
        key: database-user
```

The pattern needs to be updated to look like this:
```
  - name: DATABASE_NAME
    valueFrom:
      secretKeyRef:
        name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
        key: database-name
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
        key: database-user
```
